/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { UploadCloud, Scan, ClipboardList } from 'lucide-react';
import { motion } from 'framer-motion';

export default function HowItWorks() {
  const steps = [
    {
      stepLabel: '01',
      title: 'Upload',
      description: 'Upload a chest X-ray image (JPEG or PNG). Preview appears instantly before analysis.',
      icon: UploadCloud,
    },
    {
      stepLabel: '02',
      title: 'Analyze',
      description: 'The image is automatically resized to 224×224 pixels and processed through the RobustXrayNet deep learning model.',
      icon: Scan,
    },
    {
      stepLabel: '03',
      title: 'Results',
      description: 'Receive a Normal or Pneumonia prediction together with the confidence score generated by the model.',
      icon: ClipboardList,
    },
  ];

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.15,
      },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: [0.22, 1, 0.36, 1] } },
  };

  return (
    <section id="how-it-works" className="py-24 bg-slate-50 relative border-t border-slate-100">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}
          className="mb-16 max-w-2xl"
        >
          <h2 className="text-4xl md:text-5xl font-extrabold text-slate-900 tracking-tight">
            Three simple steps. <span className="text-blue-500">Instant AI diagnosis.</span>
          </h2>
          <p className="text-slate-500 mt-6 text-lg md:text-xl leading-relaxed">
            Upload a chest X-ray and receive an AI-assisted pneumonia prediction within seconds.
          </p>
        </motion.div>

        <motion.div 
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
          className="grid grid-cols-1 md:grid-cols-3 gap-8"
        >
          {steps.map((step, idx) => {
            const Icon = step.icon;
            return (
              <motion.div
                variants={itemVariants}
                key={idx}
                className="bg-white rounded-[2rem] p-8 md:p-10 shadow-[0_4px_20px_-4px_rgba(0,0,0,0.05)] hover:shadow-[0_8px_30px_-4px_rgba(0,0,0,0.1)] transition-shadow duration-500 border border-slate-100 flex flex-col items-start"
              >
                <div className="w-14 h-14 rounded-2xl bg-blue-500 text-white flex items-center justify-center mb-8 shadow-sm">
                  <Icon className="w-6 h-6" strokeWidth={2} />
                </div>
                <div className="flex items-center gap-2 mb-4">
                  <span className="text-sm font-mono font-bold text-slate-300">{step.stepLabel}</span>
                  <h3 className="text-2xl font-bold text-slate-900 tracking-tight">
                    {step.title}
                  </h3>
                </div>
                <p className="text-slate-500 text-base leading-relaxed">
                  {step.description}
                </p>
              </motion.div>
            );
          })}
        </motion.div>
      </div>
    </section>
  );
}
